version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - APP_TYPE=crawler
    depends_on:
      - db
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - APP_TYPE=api
    depends_on:
      - db
    ports:
      - "8081:8080"

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: